export default {
    CONNECTION_SUCCESS: '@@CONNECTION_SUCCESS',
    DISCONNECT_SUCCESS: '@@DISCONNECT_SUCCESS',
    INCOMING_EVENT: '@@INCOMING_EVENT',
    CONNECTION_ERROR: '@@CONNECTION_ERROR',
    DISCONNECT: '@@DISCONNECT'
}